[package]
name = "lyre"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lyre"
path = "src/main.rs"

[dependencies]
ratatui = { version = "0.29", features = ["unstable-rendered-line-info"] }
crossterm = "0.28"
rusqlite = { version = "0.32", features = ["bundled"] }
rodio = { version = "0.19", default-features = false }
symphonia = { version = "0.5.4", features = ["mp3", "aac", "flac", "wav", "isomp4"] }
serde = { version = "1", features = ["derive"] }
fuzzy-matcher = "0.3"
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
ratatui-image = "3.0"
lofty = "0.22"
walkdir = "2"
zbus = { version = "4", default-features = false, features = ["tokio"] }
unicode-width = "0.2"
rand = "0.8"
toml = "0.7"
rayon = "1"
clap = { version = "4", features = ["derive"] }
globset = "0.4"
indicatif = "0.17"
deunicode = "1"
strsim = "0.11"
inquire = "0.7"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }

[profile.release]
opt-level = 3       # Optimize for speed
lto = true          # Enable Link Time Optimization (speed + size)
codegen-units = 1   # Better optimization (slower compile)
strip = true        # Strip symbols from binary
panic = "abort"     # Reduce binary size by removing unwinding